In [23]:
import numpy as np
from PIL import Image
from helper import utilty as util

In [24]:
imageDefault = util.load_image('/home/jyothisable/P.A.R.A/1.Projects/mtp/ML/dcscn-super-resolution/data/bsd100/img_001.png')
ImageNew = util.load_image(
    '/home/jyothisable/P.A.R.A/1.Projects/mtp/Softwares/VS code/Solar_Insolation_Calculator/data/outputs/0.25@0.25km_train/0.25@0.25km_jamnagar_D2_H11.5.tif')
# image = Image.open(filename)
# image = image.convert(mode='RGB')
# data = np.asarray(image)

Loaded [/home/jyothisable/P.A.R.A/1.Projects/mtp/ML/dcscn-super-resolution/data/bsd100/img_001.png]: 320 x 480 x 3
Loaded [/home/jyothisable/P.A.R.A/1.Projects/mtp/Softwares/VS code/Solar_Insolation_Calculator/data/outputs/0.25@0.25km_train/0.25@0.25km_jamnagar_D2_H11.5.tif]: 304 x 208 x 1


In [25]:
print(imageDefault[0],ImageNew[0])

[[201 200 196]
 [1377 1377 251]
 [1377 1377 253]
 [254 254 252]
 [253 253 253]
 [1377 1377 1377]
 [250 250 250]
 [1377 1377 1377]
 [1377 1377 253]
 [164 163 161]
 [250 249 245]
 [1377 254 250]
 [1377 1377 251]
 [1377 1377 251]
 [251 253 248]
 [1377 1377 250]
 [250 246 235]
 [1377 249 239]
 [1377 252 250]
 [1377 252 253]
 [1377 251 254]
 [248 242 244]
 [252 248 249]
 [252 1377 248]
 [251 1377 244]
 [226 241 218]
 [171 191 163]
 [173 197 165]
 [160 185 155]
 [155 180 151]
 [147 171 145]
 [145 168 142]
 [143 161 137]
 [113 129 103]
 [110 122 102]
 [109 118 101]
 [ 90  96  84]
 [124 127 118]
 [207 206 202]
 [242 241 237]
 [232 228 225]
 [243 239 236]
 [1377 253 250]
 [251 250 246]
 [246 245 241]
 [252 253 248]
 [254 1377 251]
 [254 1377 251]
 [1377 254 1377]
 [254 252 253]
 [1377 254 252]
 [231 230 228]
 [242 241 237]
 [1377 1377 251]
 [1377 254 249]
 [1377 1377 250]
 [1377 1377 251]
 [1377 1377 251]
 [1377 1377 253]
 [1377 1377 253]
 [1377 254 1377]
 [1377 254 1377]
 [253 253 1377]
 [1377

In [26]:
util.save_image('test/imageDefault.bmp',imageDefault)
util.save_image('test/ImageNew.bmp',ImageNew)

Saved [test/imageDefault.bmp]
Saved [test/ImageNew.bmp]
