In [10]:
import numpy as np
from PIL import Image
from helper import utilty as util

In [11]:
image = Image.open(
    '/home/jyothisable/P.A.R.A/1.Projects/mtp/Softwares/VS code/Solar_Insolation_Calculator/data/outputs/0.25@0.25km_train/0.25@0.25km_jamnagar_D2_H11.5.tif')
# image = image.convert(mode='RGB')
data = np.asarray(image)

In [12]:
print(data)

[[470.6174  474.80325 466.3306  ... 477.4859  467.72986 462.11664]
 [464.11346 456.99084 460.7448  ... 461.3326  448.4501  457.11682]
 [457.19992 455.09784 457.11395 ... 467.585   459.1278  472.0081 ]
 ...
 [487.1461  491.4656  480.9423  ... 465.07117 478.35147 460.41882]
 [520.896   484.2661  486.4381  ... 445.35037 488.6854  473.9419 ]
 [489.0587  482.74536 478.22702 ... 283.8146  283.75568 482.8126 ]]
